# -*- coding: utf-8 -*-
"""Assignment 5LetsUpgrade
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1VLlDRwuQLV-mzuyEmtWbqngBkynCSFQ3
"""

# Build toutube downloader app using library in python using refer pypi.org

pip install pytube

import pytube

url = 'https://youtu.be/rIGTaG-xW8s'

youtube = pytube.YouTube(url)
video = youtube.streams.first()
video.download('../Video')
